language: go

go_import_path: github.com/lpmatos/gen

branches:
  only:
    - master

go:
  - master

before_install:
  - go get -v golang.org/x/lint/golint
  - go get -v github.com/client9/misspell/cmd/misspell

install:
  - make ginstall

script:
  - make glint
  - make misspell

notifications:
  email: luccapsm@gmail.com
