name: Linter

on:
  push:
    branches: [ master ]
    
jobs:
  linter:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3.0.0
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v1.21
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tool_name: golangci-lint
