name: Go Release

on:
  push:
    tags:
    - 'v*'

jobs:
  goreleaser:
    name: "Create Go Release"
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Extract Git Variables
        id: extract_branch
        shell: bash
        run: |
          echo Reserved for REPO_NAME=${GITHUB_REPOSITORY##*/}
          echo GITHUB_REF=${GITHUB_REF}
          echo EXTRACT_GITHUB_REF=${GITHUB_REF##*/}
          echo EXTRACT_GITHUB_REF_HEADS=$(echo ${GITHUB_REF#refs/heads/})
          echo "GIT_BRANCH=$EXTRACT_GITHUB_REF" >> $GITHUB_ENV

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - 
        name: Extract GoReleaser Variables
        run: |
          echo "CLIENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "GO_VERSION=$(go version)" >> $GITHUB_ENV

      - 
        name: Show Variables
        run: |
          echo "Client Version ${{ env.CLIENT_VERSION }}"
          echo "Git Branch ${{ env.GIT_BRANCH }}"
          echo "Go Version ${{ env.GO_VERSION }}"
