name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - 
        name: Setup Go Releaser
        run: |
          echo "CLIENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "GIT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "GO_VERSION=$(go version)" >> $GITHUB_ENV

      - 
        name: Show Variables
        run: |
          echo "Client Version ${{ env.CLIENT_VERSION }}"
          echo "Git Branch ${{ env.GIT_BRANCH }}"
          echo "Go Version ${{ env.GO_VERSION }}"

      -
        name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
