name: goreleaser

on:
  push:
    tags:
      - '*'

env:
  NODE_VERSION: "12.x"
  APP_VERSION: "1.0.O"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - 
        name: Setup GoReleaser
        id: set
        run: |
          echo "::set-env name=CLIENT_VERSION::$(cat VERSION)"
      - 
        name: use output
        run: |
          echo $CLIENT_VERSION
          echo ${{env.CLIENT_VERSION }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
