name: goreleaser

on:
  push:
    branches: [ master ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      -
        name: Git
        run: |
          git_branch=${GITHUB_REF##*/}
          echo $git_branch
          echo "GIT_BRANCH=$git_branch" >> $GITHUB_ENV

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - 
        name: Setup Go Releaser
        run: |
          echo "CLIENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "GO_VERSION=$(go version)" >> $GITHUB_ENV

      - 
        name: Show Variables
        run: |
          echo "Client Version ${{ env.CLIENT_VERSION }}"
          echo "Git Branch ${{ env.GIT_BRANCH }}"
          echo "Go Version ${{ env.GO_VERSION }}"
