name: Go Release

on:
  push:
    tags:
    - 'v*'

jobs:
  goreleaser:
    name: "Create Go Release"
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      -
        name: Extract Git Variables
        id: extract_git_variables
        shell: bash
        run: |
          echo EXTRACT_GITHUB_REF=${GITHUB_REF##*/}
          echo "GIT_BRANCH=$EXTRACT_GITHUB_REF" >> $GITHUB_ENV

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - 
        name: Extract GoReleaser Variables
        id: extract_goreleaser_variables
        run: |
          echo "CLIENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "GO_VERSION=$(go version)" >> $GITHUB_ENV

      - 
        name: Show Variables
        run: |
          echo "Git Branch ${{ env.GIT_BRANCH }}"
          echo "Client Version ${{ env.CLIENT_VERSION }}"
          echo "Go Version ${{ env.GO_VERSION }}"

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
